//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cve.Impuestos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Impuestos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Impuestos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cve.Impuestos.Properties.Impuestos", typeof(Impuestos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;2.0&quot;
        ///xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///xmlns:sii=&quot;http://www.sii.cl/SiiDte&quot;
        ///xmlns:str=&quot;http://exslt.org/strings&quot;
        ///extension-element-prefixes=&quot;str sii&quot;
        ///                xmlns:ms=&quot;urn:schemas-microsoft-com:xslt&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///	&lt;xsl:param name=&quot;TedTimbre&quot;&gt; &lt;/xsl:param&gt;
        ///	&lt;xsl:variable name=&quot;FechaHora&quot; select=&quot;/sii:DTE/sii:Documento/sii:Encabezado/sii:IdDoc/sii:FchEmis|
        ///									   /DTE/Documento [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Custodium {
            get {
                return ResourceManager.GetString("Custodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/of_confirma_folio.
        /// </summary>
        internal static string UrlConfirmaFolio {
            get {
                return ResourceManager.GetString("UrlConfirmaFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/ce_consulta_rut.
        /// </summary>
        internal static string UrlContribuyente {
            get {
                return ResourceManager.GetString("UrlContribuyente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/ce_consulta_e.
        /// </summary>
        internal static string UrlContribuyenteByRut {
            get {
                return ResourceManager.GetString("UrlContribuyenteByRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/ce_empresas_dwnld.
        /// </summary>
        internal static string UrlContribuyenteFile {
            get {
                return ResourceManager.GetString("UrlContribuyenteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/consdcvinternetui/services/data/facadeService/getDetalleVentaExport.
        /// </summary>
        internal static string UrlExportCvsEmitidos {
            get {
                return ResourceManager.GetString("UrlExportCvsEmitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/consdcvinternetui/services/data/facadeService/getDetalleCompraExport.
        /// </summary>
        internal static string UrlExportCvsRecibidos {
            get {
                return ResourceManager.GetString("UrlExportCvsRecibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/of_genera_archivo.
        /// </summary>
        internal static string UrlGeneraArchivo {
            get {
                return ResourceManager.GetString("UrlGeneraArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/of_genera_folio.
        /// </summary>
        internal static string UrlGeneraFolio {
            get {
                return ResourceManager.GetString("UrlGeneraFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://zeus.sii.cl/cvc_cgi/stc/CViewCaptcha.cgi.
        /// </summary>
        internal static string UrlGetCaptcha {
            get {
                return ResourceManager.GetString("UrlGetCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/consdcvinternetui/services/data/facadeService/getDetalleVenta.
        /// </summary>
        internal static string UrlMisDteEmitidos {
            get {
                return ResourceManager.GetString("UrlMisDteEmitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/consdcvinternetui/services/data/facadeService/getDetalleCompra.
        /// </summary>
        internal static string UrlMisDteRecibidos {
            get {
                return ResourceManager.GetString("UrlMisDteRecibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/consdcvinternetui/services/data/facadeService/getResumen.
        /// </summary>
        internal static string UrlMisDteResumen {
            get {
                return ResourceManager.GetString("UrlMisDteResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/rf_reobtencion1_folios.
        /// </summary>
        internal static string UrlReObtencionConecta {
            get {
                return ResourceManager.GetString("UrlReObtencionConecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/rf_reobtencion3_folios.
        /// </summary>
        internal static string UrlReObtencionConfirma {
            get {
                return ResourceManager.GetString("UrlReObtencionConfirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/rf_reobtencion2_folios.
        /// </summary>
        internal static string UrlReObtencionFolios {
            get {
                return ResourceManager.GetString("UrlReObtencionFolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/rf_genera_archivo.
        /// </summary>
        internal static string UrlReObtencionGeneraArchivo {
            get {
                return ResourceManager.GetString("UrlReObtencionGeneraArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/rf_genera_folio.
        /// </summary>
        internal static string UrlReObtencionGeneraFolio {
            get {
                return ResourceManager.GetString("UrlReObtencionGeneraFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://zeus.sii.cl/cvc_cgi/stc/getstc.
        /// </summary>
        internal static string UrlSituacionTributariaTerceros {
            get {
                return ResourceManager.GetString("UrlSituacionTributariaTerceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://palena.sii.cl/cvc_cgi/dte/of_solicita_folios_dcto.
        /// </summary>
        internal static string UrlSolicitaFolios {
            get {
                return ResourceManager.GetString("UrlSolicitaFolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://hercules.sii.cl/cgi_AUT2000/autInicio.cgi.
        /// </summary>
        internal static string UrlTokenSeed {
            get {
                return ResourceManager.GetString("UrlTokenSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www4.sii.cl/registrorechazodtej6ui/services/data/facadeService/validarAccesoReceptor.
        /// </summary>
        internal static string UrlValidaDte {
            get {
                return ResourceManager.GetString("UrlValidaDte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://ws1.sii.cl/WSREGISTRORECLAMODTE/registroreclamodteservice.
        /// </summary>
        internal static string WsdlRegistroReclamoDte {
            get {
                return ResourceManager.GetString("WsdlRegistroReclamoDte", resourceCulture);
            }
        }
    }
}
