//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cve.Coordinador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Coordinador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coordinador() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cve.Coordinador.Properties.Coordinador", typeof(Coordinador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/agents/.
        /// </summary>
        internal static string UrlAgents {
            get {
                return ResourceManager.GetString("UrlAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/billing-types/.
        /// </summary>
        internal static string UrlBillingTypes {
            get {
                return ResourceManager.GetString("UrlBillingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/billing-windows/.
        /// </summary>
        internal static string UrlBillingWindows {
            get {
                return ResourceManager.GetString("UrlBillingWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/operations/creditor-dte-load-jobs/create/.
        /// </summary>
        internal static string UrlCreateJob {
            get {
                return ResourceManager.GetString("UrlCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/dtes/.
        /// </summary>
        internal static string UrlDtes {
            get {
                return ResourceManager.GetString("UrlDtes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/participants/{0}/regenerate_sftp/.
        /// </summary>
        internal static string UrlFtp {
            get {
                return ResourceManager.GetString("UrlFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/instructions/.
        /// </summary>
        internal static string UrlInstruccionesv1 {
            get {
                return ResourceManager.GetString("UrlInstruccionesv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v2/resources/instructions/.
        /// </summary>
        internal static string UrlInstruccionesv2 {
            get {
                return ResourceManager.GetString("UrlInstruccionesv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/participants/.
        /// </summary>
        internal static string UrlParticipants {
            get {
                return ResourceManager.GetString("UrlParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/payment-matrices/.
        /// </summary>
        internal static string UrlPaymentMatrices {
            get {
                return ResourceManager.GetString("UrlPaymentMatrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v2/resources/periods/.
        /// </summary>
        internal static string UrlPeriods {
            get {
                return ResourceManager.GetString("UrlPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/operations/creditor-dte-load-jobs/{}/publish/.
        /// </summary>
        internal static string UrlPublicarJob {
            get {
                return ResourceManager.GetString("UrlPublicarJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/v1/resources/auxiliary-files/.
        /// </summary>
        internal static string UrlPutFiles {
            get {
                return ResourceManager.GetString("UrlPutFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /api/token-auth/.
        /// </summary>
        internal static string UrlTokenAuth {
            get {
                return ResourceManager.GetString("UrlTokenAuth", resourceCulture);
            }
        }
    }
}
